#!/bin/sh

_hubImage='xfrocks/tarsnap'
_hubImageWithTag="$_hubImage:1.0.39"

docker build . \
  -t "$_hubImage" \
  -t "$_hubImageWithTag"

while true
do
  read -p "Push ${_hubImage} and ${_hubImageWithTag}? [yN]" yn
  case $yn in
    [Yy]* ) break;;
    * )
      exit 0;;
  esac
done
docker push "${_hubImage}:latest"
docker push "${_hubImageWithTag}"
